"""Cambio Guardian

Revision ID: bc33cb0ce45a
Revises: cbdce11d94f7
Create Date: 2025-09-19 17:48:17.785641

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bc33cb0ce45a'
down_revision = 'cbdce11d94f7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('children', schema=None) as batch_op:
        batch_op.drop_column('allow_whatsapp')

    with op.batch_alter_table('guardians', schema=None) as batch_op:
        batch_op.add_column(sa.Column('allow_whatsapp_group', sa.Boolean(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('guardians', schema=None) as batch_op:
        batch_op.drop_column('allow_whatsapp_group')

    with op.batch_alter_table('children', schema=None) as batch_op:
        batch_op.add_column(sa.Column('allow_whatsapp', sa.BOOLEAN(), nullable=False))

    # ### end Alembic commands ###
