"""reglamento

Revision ID: fb1d4cb95230
Revises: 3c18aaacf398
Create Date: 2025-09-22 12:43:08.451931

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fb1d4cb95230'
down_revision = '3c18aaacf398'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('subscriptions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reglamento_accepted_at', sa.DateTime(timezone=True), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('subscriptions', schema=None) as batch_op:
        batch_op.drop_column('reglamento_accepted_at')

    # ### end Alembic commands ###
